services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:5173"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    environment:
      - NODE_ENV=development
      - API_URL=http://backend:8000
    command: sh -c "cd react-app-ocr && npm install && npm run dev -- --host"
    stdin_open: true
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge